### ISSUE TITLE
Add meta/main.yml / publish on Ansible Galaxy

### ISSUE THREAD

**Issue by strarsis** [adleviton/trellis-wordfence#1]
@adleviton: For installing this role using `ansible-galaxy`, 
it apparently needs a `meta/main.yml` file in this repository. 
It would also great to have this published on Ansible Galaxy.

**Comment by strarsis** [comment]
PR: https://github.com/adleviton/trellis-wordfence/pull/2

**Comment by adleviton** [comment]
Thank you @strarsis:

https://galaxy.ansible.com/adleviton/trellis_wordfence

note name change for deploy-hooks/build-after.yml

```
- name: Setup Wordfence
  include_role:
    name: trellis_wordfence
```
