### ISSUE TITLE
PHP Warnings when using WP-CLI

### ISSUE THREAD

**Issue by stuartcusackie** [adleviton/trellis-wordfence#3]
Hi. Your package works great but I get these warnings every time I run a WP-CLI command now:

`PHP Warning:  fopen(/srv/www/mysite.uk/releases/20200515102053/web/app/wflogs/rules.php): failed to open stream: No such file or directory in /srv/www/mysite.uk/releases/20200515102053/web/app/plugins/wordfence/vendor/wordfence/wf-waf/src/lib/waf.php on line 325`

`PHP Warning:  flock() expects parameter 1 to be resource, bool given in /srv/www/mysite.uk/releases/20200515102053/web/app/plugins/wordfence/vendor/wordfence/wf-waf/src/lib/waf.php on line 326`

Any ideas?

**Comment by adleviton** [comment]
Try adding this to the wp-cli.yml file:

```
skip-plugins:
  - wordfence

```

**Comment by stuartcusackie** [comment]
Excellent! Thanks for this.
